# Generated by Django 3.2.12 on 2022-02-25 19:15

from django.db import migrations, models
from counterapp.models import Counter



def add_default_counter(apps, schema_editor):
    Counter.objects.create(name='default')

def remove_default_counter(apps, schema_editor):
    Counter.objects.all().delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RunPython(
            add_default_counter, remove_default_counter
        )
    ]
